export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";
export const FETCHING_IMAGES = "FETCHING_IMAGES";
export const FETCHING_IMAGES_SUCCESS = "FETCHING_IMAGES_SUCCESS";